export {default as Menu} from './Menu/Menu'
export {default as Menu2} from './Menu/Menu2'
export {default as Navbar} from './Navbar/Navbar'
export {default as Navbar2} from './Navbar/Navbar2'
export {default as CreateClass } from './Create/CreateClass'
export {default as JoinClass } from './Join/JoinClass'
export {default as Login } from './Login/Signin'
export {default as Signup } from './Login/Signup'
export {default as Logout } from './Login/Logout'
export {default as ForgotPassword } from './Login/ForgotPassword'
export {default as UpdateProfile } from './Login/UpdateProfile'
export {default as JoinedClasses } from './Joined/JoinedClasses'
export {default as Class } from './Class/Class'
export {default as CreateQuiz } from './Quiz/CreateQuiz'
export {default as JoinQuiz } from './Quiz/JoinQuiz'
export {default as RealTimeResults } from './Quiz/RealTimeResults'